### ISSUE TITLE
Publish this project to LuaRocks

### ISSUE THREAD

**Issue by bungle** [tokers/lua-resty-http2#2]
This is great! Would you like to publish this to LuaRocks?

**Comment by tokers** [comment]
@bungle 
Yes! I really want to. But currently this project is still semi-finished, some crucial factors are pendent.

* The `sslhandshake` method of Cosocket should support the ALPN/NPN extensions.
* A user data binding mechanism should be created for Cosocket .

I have a [patch](https://github.com/tokers/lua-resty-http2/blob/master/util/lua-nginx-module-0.10.13-ssl-alpn.patch) in this repository to solve the first problem, I'd like to improve this patch and contribute it to lua-nginx-module.

For the other one, there is a opened [Pull Request](https://github.com/openresty/lua-nginx-module/pull/712) in lua-nginx-module.

I will keep this issue until we solve these two problems. :)

**Comment by bungle** [comment]
@tokers,

Thanks! I will look if I have time, meanwhile, to add PR for you that adds the rockspec.

**Comment by tokers** [comment]
@bungle 
Oh. Thanks a lot!

**Comment by tokers** [comment]
@bungle 
We have published this repo to LuaRocks now. See https://github.com/tokers/lua-resty-http2/pull/3 for the details.
